[workspace]
members = ["workloads/Test/harness"]

[package]
name = "etna"
version = "0.1.16"
edition = "2021"
default-run = "etna"
repository = "https://github.com/alpaylan/etna-cli"

[dependencies]
ab_glyph = "0.2.30"
anyhow = "1.0.88"
base64 = "0.22"
axum = { version = "0.8", features = ["macros"] }
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.17", features = ["derive"] }
dirs = "5.0.1"
env_logger = "0.11.5"
flate2 = "1"
git2 = { version = "0.19.0", default-features = false, features = ["https", "vendored-openssl"] }
image = { version = "0.25.6", default-features = false, features = ["png"] }
imageproc = { version = "0.25.0", default-features = false }
itertools = { version = "0.14.0" }
marauders = { git = "https://github.com/alpaylan/marauders.git", branch = "main" }
minijinja = { version = "2.12.0", default-features = false, features = ["loader", "serde"] }
parse_duration = { version = "2.1.1", default-features = false }
process_control = { version = "5.0.0", default-features = false }
regex = "1.11.2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0.210", default-features = false }
serde_derive = { version = "1.0.210", default-features = false }
serde_json = { version = "1.0.128", default-features = false, features = ["preserve_order"] }
tabled = { version = "0.16.0", default-features = false, features = ["std"] }
tempfile = "3.20.0"
tokio = { version = "1", features = ["full"] }
toml = { version = "0.8.19", default-features = false, features = ["parse"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "ansi"] }
tracing-appender = "0.2"
rayon = "1.11.0"
uuid = { version = "1.0", features = ["v4"] }
clap_complete = "4.6.2"

[[bin]]
name = "etna"
path = "src/cli.rs"


[[bin]]
name = "etna-server"
path = "src/bin/etna-server.rs"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
serial_test = "3"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
