#!/usr/bin/env bash
# Bulk-rollout: open a PR adding `.github/workflows/etna-publish.yml` to every
# stable workload in `docs/workloads/index.json`.
#
# Idempotent — skips repos that already have an `etna-publish.yml` workflow.
# Skips entries with `status != "stable"` and entries tagged `wip`.
# One PR per repo so each can be reviewed (or batch-merged with `gh pr merge`).
#
# Usage:
#   scripts/scaffold-publish-workflow.sh [--ref <gha-ref>] [--dry-run] [--limit N]
#     --ref <ref>     Reusable-workflow ref (default: v0.1.10).
#                     During testing pass --ref add-publish-page to track the
#                     PR branch.
#     --dry-run       Print actions but don't push or open PRs.
#     --limit N       Only process the first N entries (handy for canary).
#
# Required env:
#   GH_TOKEN with `repo` scope (or `gh auth login`).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ETNA_REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
INDEX_JSON="$ETNA_REPO/docs/workloads/index.json"

REF="v0.1.10"
DRY_RUN=0
LIMIT=999

while [ $# -gt 0 ]; do
  case "$1" in
    --ref)     REF="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --limit)   LIMIT="$2"; shift 2 ;;
    -h|--help) sed -n '2,18p' "$0"; exit 0 ;;
    *)         echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ ! -f "$INDEX_JSON" ]; then
  echo "[scaffold] index.json not found at $INDEX_JSON" >&2
  exit 1
fi

WORKFLOW_FILE_NAME="etna-publish.yml"
WORKFLOW_PATH=".github/workflows/$WORKFLOW_FILE_NAME"

emit_workflow() {
  local ref="$1"
  cat <<EOF
name: Publish experiment results

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**.md'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  publish:
    uses: alpaylan/etna-cli/.github/workflows/run-and-publish.yml@$ref
    with:
      trials: 10
      timeout: 60
    secrets:
      CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
EOF
}

# Iterate stable, non-wip entries.
mapfile -t ENTRIES < <(
  python3 - <<PY
import json, sys
data = json.load(open("$INDEX_JSON"))
for e in data["entries"]:
    if e.get("status") != "stable":
        continue
    if "wip" in e.get("tags", []):
        continue
    print(f"{e['name']}\t{e['url']}")
PY
)

count=0
for entry in "${ENTRIES[@]}"; do
  count=$((count + 1))
  if [ "$count" -gt "$LIMIT" ]; then break; fi

  name="${entry%%$'\t'*}"
  url="${entry##*$'\t'}"
  owner_repo="${url#https://github.com/}"
  owner_repo="${owner_repo%.git}"

  echo
  echo "[scaffold] [$count] $name -> $owner_repo (ref=$REF)"

  # Skip if the workflow already exists on the repo's default branch.
  if gh api "repos/$owner_repo/contents/$WORKFLOW_PATH" >/dev/null 2>&1; then
    echo "[scaffold]   already has $WORKFLOW_PATH; skipping"
    continue
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    echo "[scaffold]   (dry-run) would PR $WORKFLOW_PATH"
    continue
  fi

  # Check out a working tree, drop the workflow, push a branch, open a PR.
  workdir=$(mktemp -d)
  trap 'rm -rf "$workdir"' RETURN
  if ! git clone --depth=1 "$url" "$workdir" >/dev/null 2>&1; then
    echo "[scaffold]   clone failed; skipping"
    continue
  fi
  default_branch=$(git -C "$workdir" symbolic-ref --short HEAD)
  branch="ci/etna-publish"

  git -C "$workdir" checkout -b "$branch"
  mkdir -p "$workdir/.github/workflows"
  emit_workflow "$REF" > "$workdir/$WORKFLOW_PATH"
  git -C "$workdir" add "$WORKFLOW_PATH"
  if ! git -C "$workdir" -c user.email=etna-ify@local -c user.name="ETNA Bootstrap" \
       commit -qm "ci: add etna-publish workflow"; then
    echo "[scaffold]   no changes to commit (workflow already up to date); skipping"
    continue
  fi

  if ! git -C "$workdir" push -q origin "$branch"; then
    echo "[scaffold]   push failed; skipping"
    continue
  fi

  gh -R "$owner_repo" pr create --base "$default_branch" --head "$branch" \
    --title "ci: add etna-publish workflow" \
    --body "Calls \`alpaylan/etna-cli/.github/workflows/run-and-publish.yml@$REF\` on every push to \`$default_branch\` and on workflow_dispatch. Deploys results to \`https://$name.pages.dev\` with a \`/report.json\` endpoint.

Required secrets at the repo (or org) level:
- \`CLOUDFLARE_API_TOKEN\`
- \`CLOUDFLARE_ACCOUNT_ID\`

Generated by \`etna-cli/scripts/scaffold-publish-workflow.sh\`." \
    || { echo "[scaffold]   pr create failed; skipping"; continue; }

  echo "[scaffold]   ok"
done

echo
echo "[scaffold] done — processed $count entr(ies); pass --limit to scope; --dry-run to preview"
